version: '3.8'

services:
  nba-bot:
    build: .
    container_name: nba_bot
    restart: unless-stopped
    volumes:
      - ./nba_bot.db:/app/nba_bot.db
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    
  stopper:
    build: .
    container_name: nba_bot_stopper
    restart: unless-stopped
    command: python stopper.py
    volumes:
      - ./nba_bot.db:/app/nba_bot.db
      - ./logs:/app/logs
    depends_on:
      - nba-bot

  updater:
    build: .
    container_name: nba_bot_updater
    restart: unless-stopped
    command: python atualizar_calendario.py
    volumes:
      - ./nba_bot.db:/app/nba_bot.db
      - ./logs:/app/logs